<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://infor.com/pcm/v2" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ProductConfiguratorUI" targetNamespace="http://infor.com/pcm/v2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="CustomBinding_ProductConfiguratorUIServiceProxy_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:ProtectionToken>
              <wsp:Policy>
                <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:RequireDerivedKeys />
                    <sp:BootstrapPolicy>
                      <wsp:Policy>
                        <sp:SignedParts>
                          <sp:Body />
                          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
                        </sp:SignedParts>
                        <sp:EncryptedParts>
                          <sp:Body />
                        </sp:EncryptedParts>
                        <sp:SymmetricBinding>
                          <wsp:Policy>
                            <sp:ProtectionToken>
                              <wsp:Policy>
                                <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                                  <wsp:Policy>
                                    <sp:RequireDerivedKeys />
                                  </wsp:Policy>
                                </sp:SpnegoContextToken>
                              </wsp:Policy>
                            </sp:ProtectionToken>
                            <sp:AlgorithmSuite>
                              <wsp:Policy>
                                <sp:Basic256 />
                              </wsp:Policy>
                            </sp:AlgorithmSuite>
                            <sp:Layout>
                              <wsp:Policy>
                                <sp:Strict />
                              </wsp:Policy>
                            </sp:Layout>
                            <sp:IncludeTimestamp />
                            <sp:EncryptSignature />
                            <sp:OnlySignEntireHeadersAndBody />
                          </wsp:Policy>
                        </sp:SymmetricBinding>
                        <sp:Wss11>
                          <wsp:Policy />
                        </sp:Wss11>
                        <sp:Trust10>
                          <wsp:Policy>
                            <sp:MustSupportIssuedTokens />
                            <sp:RequireClientEntropy />
                            <sp:RequireServerEntropy />
                          </wsp:Policy>
                        </sp:Trust10>
                      </wsp:Policy>
                    </sp:BootstrapPolicy>
                  </wsp:Policy>
                </sp:SecureConversationToken>
              </wsp:Policy>
            </sp:ProtectionToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
            <sp:EncryptSignature />
            <sp:OnlySignEntireHeadersAndBody />
          </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy />
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_InitializeConfiguration_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_InitializeConfiguration_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_Configure_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_Configure_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_FinalizeConfiguration_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_FinalizeConfiguration_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_SavePartialConfiguration_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_SavePartialConfiguration_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_SaveFullConfiguration_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_SaveFullConfiguration_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_CancelConfiguration_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_ProductConfiguratorUIServiceProxy_CancelConfiguration_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://infor.com/pcm/v2/Imports">
      <xsd:import schemaLocation="http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc?xsd=xsd0" namespace="http://infor.com/pcm/v2" />
      <xsd:import schemaLocation="http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_InitializeConfiguration_InputMessage">
    <wsdl:part name="parameters" element="tns:InitializeConfiguration" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_InitializeConfiguration_OutputMessage">
    <wsdl:part name="parameters" element="tns:InitializeConfigurationResponse" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_Configure_InputMessage">
    <wsdl:part name="parameters" element="tns:Configure" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_Configure_OutputMessage">
    <wsdl:part name="parameters" element="tns:ConfigureResponse" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_FinalizeConfiguration_InputMessage">
    <wsdl:part name="parameters" element="tns:FinalizeConfiguration" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_FinalizeConfiguration_OutputMessage">
    <wsdl:part name="parameters" element="tns:FinalizeConfigurationResponse" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_SavePartialConfiguration_InputMessage">
    <wsdl:part name="parameters" element="tns:SavePartialConfiguration" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_SavePartialConfiguration_OutputMessage">
    <wsdl:part name="parameters" element="tns:SavePartialConfigurationResponse" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_SaveFullConfiguration_InputMessage">
    <wsdl:part name="parameters" element="tns:SaveFullConfiguration" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_SaveFullConfiguration_OutputMessage">
    <wsdl:part name="parameters" element="tns:SaveFullConfigurationResponse" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_CancelConfiguration_InputMessage">
    <wsdl:part name="parameters" element="tns:CancelConfiguration" />
  </wsdl:message>
  <wsdl:message name="ProductConfiguratorUIServiceProxy_CancelConfiguration_OutputMessage">
    <wsdl:part name="parameters" element="tns:CancelConfigurationResponse" />
  </wsdl:message>
  <wsdl:portType name="ProductConfiguratorUIServiceProxy">
    <wsdl:operation name="InitializeConfiguration">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/InitializeConfiguration" message="tns:ProductConfiguratorUIServiceProxy_InitializeConfiguration_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/InitializeConfigurationResponse" message="tns:ProductConfiguratorUIServiceProxy_InitializeConfiguration_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="Configure">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/Configure" message="tns:ProductConfiguratorUIServiceProxy_Configure_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/ConfigureResponse" message="tns:ProductConfiguratorUIServiceProxy_Configure_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="FinalizeConfiguration">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/FinalizeConfiguration" message="tns:ProductConfiguratorUIServiceProxy_FinalizeConfiguration_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/FinalizeConfigurationResponse" message="tns:ProductConfiguratorUIServiceProxy_FinalizeConfiguration_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="SavePartialConfiguration">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SavePartialConfiguration" message="tns:ProductConfiguratorUIServiceProxy_SavePartialConfiguration_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SavePartialConfigurationResponse" message="tns:ProductConfiguratorUIServiceProxy_SavePartialConfiguration_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="SaveFullConfiguration">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SaveFullConfiguration" message="tns:ProductConfiguratorUIServiceProxy_SaveFullConfiguration_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SaveFullConfigurationResponse" message="tns:ProductConfiguratorUIServiceProxy_SaveFullConfiguration_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation name="CancelConfiguration">
      <wsdl:input wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/CancelConfiguration" message="tns:ProductConfiguratorUIServiceProxy_CancelConfiguration_InputMessage" />
      <wsdl:output wsaw:Action="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/CancelConfigurationResponse" message="tns:ProductConfiguratorUIServiceProxy_CancelConfiguration_OutputMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="CustomBinding_ProductConfiguratorUIServiceProxy" type="tns:ProductConfiguratorUIServiceProxy">
    <wsp:PolicyReference URI="#CustomBinding_ProductConfiguratorUIServiceProxy_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="InitializeConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/InitializeConfiguration" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Configure">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/Configure" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="FinalizeConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/FinalizeConfiguration" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SavePartialConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SavePartialConfiguration" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SaveFullConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SaveFullConfiguration" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/CancelConfiguration" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="BasicHttpBinding_ProductConfiguratorUIServiceProxy" type="tns:ProductConfiguratorUIServiceProxy">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="InitializeConfiguration">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/InitializeConfiguration" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Configure">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/Configure" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="FinalizeConfiguration">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/FinalizeConfiguration" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SavePartialConfiguration">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SavePartialConfiguration" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SaveFullConfiguration">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SaveFullConfiguration" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelConfiguration">
      <soap:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/CancelConfiguration" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="WSHttpBinding_ProductConfiguratorUIServiceProxy" type="tns:ProductConfiguratorUIServiceProxy">
    <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="InitializeConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/InitializeConfiguration" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_InitializeConfiguration_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_InitializeConfiguration_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Configure">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/Configure" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_Configure_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_Configure_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="FinalizeConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/FinalizeConfiguration" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_FinalizeConfiguration_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_FinalizeConfiguration_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SavePartialConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SavePartialConfiguration" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_SavePartialConfiguration_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_SavePartialConfiguration_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="SaveFullConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/SaveFullConfiguration" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_SaveFullConfiguration_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_SaveFullConfiguration_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelConfiguration">
      <soap12:operation soapAction="http://infor.com/pcm/v2/ProductConfiguratorUIServiceProxy/CancelConfiguration" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_CancelConfiguration_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_ProductConfiguratorUIServiceProxy_CancelConfiguration_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ProductConfiguratorUI">
    <wsdl:port name="CustomBinding_ProductConfiguratorUIServiceProxy" binding="tns:CustomBinding_ProductConfiguratorUIServiceProxy">
      <soap12:address location="http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc</wsa10:Address>
      </wsa10:EndpointReference>
    </wsdl:port>
    <wsdl:port name="BasicHttpBinding_ProductConfiguratorUIServiceProxy" binding="tns:BasicHttpBinding_ProductConfiguratorUIServiceProxy">
      <soap:address location="http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc/basic" />
    </wsdl:port>
    <wsdl:port name="WSHttpBinding_ProductConfiguratorUIServiceProxy" binding="tns:WSHttpBinding_ProductConfiguratorUIServiceProxy">
      <soap12:address location="http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc/ws" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://216.162.180.77/PCMDEV/ConfiguratorService/v2/ProductConfiguratorUI.svc/ws</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Spn>host/SVR-VIA-APP2.via.local</Spn>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>